#http端口
http-port: 8200

#https端口
server:
  port: 8100

  #开启支持https协议，关闭支持http协议
  ssl:
    #指定keystore文件，使用类路径的方式
    key-store: classpath:dongbao-alias.keystore
    #密钥库:java keystore
    key-store-type: JKS
    #密钥别名
    key-alias: dongbao-alias
    #密钥库口令
    key-store-password: 123456
    #密钥口令
    key-password: 123456
